apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-integrations
  namespace: prod-api-rmp
  labels:
    app: service-integrations
spec:
  replicas: 3
  selector:
    matchLabels:
      app: service-integrations
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: service-integrations
    spec:
      containers:
        - name: service-integrations
          image: <IMAGE-INTEGRATIONS-SERVICE>
          ports:
            - name: http
              containerPort: 8006
          resources:
            requests:
              cpu: 100m
          envFrom:
            - configMapRef:
                name: configmap-integrations-rmp
